apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-qaautocand-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: HELM/nginx-deployment
    repoURL: https://github.com/yeswanthreddybellam/Learning
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values_qaautocand.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
