metadataname: nginx-deployment-qacand
namespace: qa-qacand
appname: nginx-qacand
ports:
 http:
  protocol: TCP
  port: 80
  targetPort: 80
  type: NodePort
 https:
  protocol: TCP
  port: 8080
  targetPort: 80
  type: ClusterIP
replicas: 2
environment: QACAND
env_variables:
  enabled: false
