apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-game-demo
  namespace: {{ .Values.namespace }}
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties" 
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
