apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-datacentername
  namespace: {{ .Values.namespace }}
data:
  datacentername: |
    { "dc25" : {
          "envi" : "{{ .Values.appname }}"
              } 
    }
