apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-game-demo
  namespace: {{ .Values.namespace }}
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"  
