{{- range $i, $e := (include "global.getHostnameList" .Values.global.zookeeper.hosts | fromYamlArray) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname  }}
data:
  dna.json: |-
    {
      "cf": {
        "nodes": {{spec.nodeName | toJson}}
      }
    }
    
