apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadataname }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: nginx
        image: hub.docker.com/yeshw/nexon
        ports:
        - containerPort: {{ .Values.cport }}
        env:
        - name: JVM
          value: "11"
        - name: MACHINE
          value: "18"
        - name: SERVER
          value: "cf111"
        - name: ENVIRONMENT
          value: {{ .Values.environment}}
        {{- if .Values.env_variables.enabled }}
        - name: Consul
          value: "True"
        {{- else }}  
        - name: Consul
          value: "False"
        {{- end }}
