apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadataname }} # Helm templating used here
  namespace: {{ .Values.namespace }} # Helm templating used here
  labels:
    app:  {{ .Values.appname }} # Helm templating used here
spec:
  replicas: {{ .Values.replicas}} # Helm templating used here
  selector:
    matchLabels:
      app: {{ .Values.appname }} # Helm templating used here
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appname }} # Helm templating used here
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: {{ .Values.cport }} # Helm templating used here
        volumeMounts:
          - name: datacenter-config
            mountPath: /app/datacenter.json
            subPath: datacenter.json
          - name: game-demo-config
            mountPath: /gamedemo-config  
        env:
        - name: JVM
          value: "11"
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appname }}-game-demo # Helm templating used here
              key: player_initial_lives
        - name: MACHINE
          value: "18"
        - name: SERVER
          value: "cf111"
        - name: ENVIRONMENT
          value: {{ .Values.environment}} # Helm templating used here
        - name: Release
          value: {{ .Release.Name }} # Helm templating used here
        {{- if .Values.env_variables.enabled }}
        - name: Consul
          value: "True"
        {{- else }}  
        - name: Consul
          value: "False"
        {{- end }}  
      volumes:
        - name: datacenter-config
          configMap:
            name: {{ .Values.appname }}-datacentername
        - name: game-demo-config
          configMap:
            name: {{ .Values.appname }}-game-demo
              
          

