apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: yeswanth.cars
      http:
        paths:
        - path: /nexon
          pathType: Prefix
          backend:
              service:
                name:  nginx-nexon-service
                port:
                  number: 8083
        - path: /agaro
          pathType: Prefix
          backend:
              service:
                name:  nginx-agaro-service
                port:
                  number: 8082 
