apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: qacand.cars
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name:  {{ .Values.appname }}-service
                port:
                  number: 80
        
