apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.cport }}
