apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
  {{- range $key, $value := .Values.ports }}
    - name: {{ $value.type }}
      protocol: {{ $value.protocol }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
    type: {{ $value.type_port }}    
  {{- end }}

