apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
  {{- range .Values.ports }}
    - name: {{ .type }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: {{ (index .Values.ports 0).type_port }}
