apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
  {{- range $key, $value := .Values.ports }}
  - name: {{$values.type}}
    protocol: {{ $values.protocol}}
    port: {{ $values.port}}
    targetPort: {{ $values.targetPort }}
  type: {{$values.type_port}}
  {{- end}}
